import { randomUUID } from 'node:crypto';
import { SCENE_ACTION_BUDGET } from '../../packages/server/ai-config.js';
import type { AiService, MediaPermit } from '../../packages/server/ai-service.js';
import {
  generateScene,
  inspectScene,
  type SceneInput,
} from '../../packages/server/image-service.js';
import type { SceneImageSlot } from '../../packages/shared/conversation.js';
import { AiServiceError } from '../../packages/server/ai-service.js';
import { UpstreamError } from '../../packages/server/openai.js';
import { ZodError } from 'zod';
import { recoverableAiError } from '../../packages/server/ai-recovery.js';

function sceneFailureCode(error: unknown): string {
  if (error instanceof AiServiceError) return 'SCENE_' + error.code;
  if (error instanceof UpstreamError && Number.isInteger(error.upstreamStatus))
    return 'SCENE_HTTP_' + error.upstreamStatus;
  if (error instanceof ZodError || error instanceof SyntaxError) return 'SCENE_INVALID_RESPONSE';
  if (error instanceof Error && ['INSPECTION_UNKNOWN', 'INSPECTION_REFUSED'].includes(error.message))
    return 'SCENE_' + error.message;
  return 'SCENE_RECEIVE_FAILED';
}
export type SceneStatus = SceneImageSlot['status'];
export interface SceneCallbacks {
  ready(jpeg: Buffer): void;
  failed(errorCode?: string, status?: 'failed' | 'cancelled'): void;
  stage?(status: SceneStatus): void;
}
export interface SceneJob {
  id: string;
  playId: string;
  messageId: string;
  deadline: number;
  status: SceneStatus;
  attempts: number;
  cancellationEpoch: number;
}
interface InternalJob extends SceneJob {
  input: SceneInput;
  callbacks: SceneCallbacks;
  permit?: MediaPermit;
  started: boolean;
  busy: boolean;
  feedback: string;
  inspectionsForImage: number;
  retryAt: number;
  errorCode?: string;
  image?: { inspection: Buffer; public: Buffer };
}
/** Finite in-memory round-robin queue; generated bytes remain private until inspection passes. */
export class SceneJobs {
  private readonly jobs = new Map<string, InternalJob>();
  private readonly completed = new Map<string, Map<string, SceneJob>>();
  private readonly activePlays = new Set<string>();
  private timer?: ReturnType<typeof setTimeout>;
  private lastPlay = '';
  private stopped = false;
  constructor(
    private readonly ai: AiService,
    private readonly options: {
      now?: () => number;
      onFailure?: (playId: string, stage: SceneStatus, errorCode: string) => void;
      onRecovery?: (playId: string, stage: SceneStatus, errorCode: string) => void;
      retryDelayMs?: number;
    } = {},
  ) {}
  private now() {
    return this.options.now?.() ?? performance.now();
  }
  enqueue(input: SceneInput, callbacks: SceneCallbacks): SceneJob {
    const job: InternalJob = {
      id: randomUUID(),
      playId: input.playId,
      messageId: input.messageId,
      input: structuredClone(input),
      callbacks,
      deadline: this.now() + this.ai.config.imageJobTimeoutMs,
      status: 'queued',
      attempts: 0,
      cancellationEpoch: 0,
      started: false,
      busy: false,
      feedback: '',
      inspectionsForImage: 0,
      retryAt: 0,
    };
    // A repeated event cannot create a second image for the same fixed message.
    const existing = [...this.jobs.values()].find(
      (j) => j.playId === input.playId && j.messageId === input.messageId,
    );
    if (existing) return this.publicJob(existing);
    const completed = this.completed.get(input.playId)?.get(input.messageId);
    if (completed) return completed;
    if (this.stopped || [...this.jobs.values()].filter((j) => !j.started).length >= 30) {
      job.status = 'failed';
      job.errorCode = this.stopped ? 'SCENE_DRAINING' : 'SCENE_QUEUE_FULL';
      this.report(job);
      callbacks.stage?.('failed');
      callbacks.failed(job.errorCode);
      return this.publicJob(job);
    }
    try {
      job.permit = this.ai.registerMedia(input.playId, job.id, job.deadline, SCENE_ACTION_BUDGET);
    } catch (error) {
      job.status = 'failed';
      callbacks.stage?.('failed');
      job.errorCode = sceneFailureCode(error);
      this.report(job);
      callbacks.failed(job.errorCode);
      return this.publicJob(job);
    }
    this.jobs.set(job.id, job);
    callbacks.stage?.('queued');
    this.schedule(0);
    return this.publicJob(job);
  }
  private publicJob(job: InternalJob): SceneJob {
    return {
      id: job.id,
      playId: job.playId,
      messageId: job.messageId,
      deadline: job.deadline,
      status: job.status,
      attempts: job.attempts,
      cancellationEpoch: job.cancellationEpoch,
    };
  }
  private schedule(delay = 25) {
    if (this.timer || this.stopped || !this.jobs.size) return;
    this.timer = setTimeout(() => {
      this.timer = undefined;
      this.pump();
    }, delay);
    this.timer.unref?.();
  }
  private setStage(job: InternalJob, status: SceneStatus) {
    job.status = status;
    job.callbacks.stage?.(status);
  }
  private report(job: InternalJob): void {
    try {
      this.options.onFailure?.(job.playId, job.status, job.errorCode ?? 'SCENE_RECEIVE_FAILED');
    } catch {
      /* Diagnostics must not interrupt cleanup. */
    }
  }
  private finish(job: InternalJob, status: 'failed' | 'cancelled' | 'ready', bytes?: Buffer) {
    if (!this.jobs.has(job.id)) return;
    this.jobs.delete(job.id);
    if (!job.busy && job.started) this.activePlays.delete(job.playId);
    this.ai.releaseMedia(job.id);
    job.image = undefined;
    if (status === 'failed') this.report(job);
    this.setStage(job, status);
    const completed = this.completed.get(job.playId) ?? new Map<string, SceneJob>();
    completed.set(job.messageId, this.publicJob(job));
    this.completed.set(job.playId, completed);
    if (status === 'ready' && bytes) job.callbacks.ready(bytes);
    else job.callbacks.failed(job.errorCode, status === 'cancelled' ? 'cancelled' : 'failed');
    this.schedule(0);
  }
  private pump() {
    for (const job of this.jobs.values())
      if (this.now() >= job.deadline) {
        job.errorCode = 'SCENE_TIMEOUT';
        this.finish(job, 'failed');
      }
    const plays = [...new Set([...this.jobs.values()].map((j) => j.playId))];
    const index = plays.indexOf(this.lastPlay);
    const order = [...plays.slice(index + 1), ...plays.slice(0, index + 1)];
    for (const play of order) {
      const job = [...this.jobs.values()].find(
        (j) => j.playId === play && !j.busy && this.now() >= j.retryAt &&
          (j.started || !this.activePlays.has(play)),
      );
      if (!job) continue;
      const kind = job.image ? 'inspection' : 'generation';
      if (this.ai.mediaDelay(kind) > 0) continue;
      this.lastPlay = play;
      job.started = true;
      job.busy = true;
      this.activePlays.add(play);
      void this.run(job).catch(() => this.finish(job, 'failed'));
    }
    this.schedule();
  }
  private async run(job: InternalJob) {
    try {
      if (!job.image) {
        this.setStage(job, job.attempts ? 'retrying' : 'generating');
        job.attempts++;
        job.inspectionsForImage = 0;
        job.image = await generateScene(
          this.ai,
          job.id,
          job.cancellationEpoch,
          job.input,
          job.feedback,
        );
        if (!this.jobs.has(job.id)) return;
        this.setStage(job, 'checking');
      } else {
        if (job.status === 'retrying') this.setStage(job, 'checking');
        job.inspectionsForImage++;
        const checked = await inspectScene(
          this.ai,
          job.id,
          job.cancellationEpoch,
          job.input,
          job.image.inspection,
        );
        if (!this.jobs.has(job.id)) return;
        if (checked.verdict === 'pass') {
          this.finish(job, 'ready', job.image.public);
          return;
        }
        if (checked.verdict === 'unknown') throw new Error('INSPECTION_UNKNOWN');
        job.feedback = JSON.stringify(checked);
        job.errorCode = checked.verdict === 'reject'
          ? 'SCENE_INSPECTION_REJECTED'
          : 'SCENE_INSPECTION_UNKNOWN';
        job.image = undefined;
        if (job.attempts >= 2) {
          this.finish(job, 'failed');
          return;
        }
        this.setStage(job, 'retrying');
      }
    } catch (error) {
      if (!this.jobs.has(job.id)) return;
      job.errorCode = sceneFailureCode(error);
      if (!recoverableAiError(error) || this.now() >= job.deadline) {
        this.finish(job, 'failed');
        return;
      }
      // A failed inspection does not invalidate the generated bytes. Check them again first.
      if (!job.image || job.inspectionsForImage >= 2) {
        job.image = undefined;
        job.feedback = 'The previous generation or inspection could not be completed. Show the confirmed state clearly.';
        if (job.attempts >= 2) {
          this.finish(job, 'failed');
          return;
        }
      }
      try {
        this.options.onRecovery?.(job.playId, job.status, job.errorCode);
      } catch { /* Diagnostics cannot interrupt a retry. */ }
      job.retryAt = this.now() + (this.options.retryDelayMs ?? 250);
      this.setStage(job, 'retrying');
    } finally {
      job.busy = false;
      if (!this.jobs.has(job.id) && job.started) this.activePlays.delete(job.playId);
      this.schedule(0);
    }
  }
  cancelPlay(playId: string, queuedOnly = false) {
    for (const job of this.jobs.values())
      if (job.playId === playId && (!queuedOnly || !job.started)) {
        job.cancellationEpoch++;
        this.finish(job, 'cancelled');
      }
  }
  cancelAll() {
    this.stopped = true;
    if (this.timer) clearTimeout(this.timer);
    this.timer = undefined;
    for (const job of this.jobs.values()) {
      job.cancellationEpoch++;
      this.finish(job, 'cancelled');
    }
    this.completed.clear();
  }
  forgetPlay(playId: string) {
    this.cancelPlay(playId);
    this.completed.delete(playId);
  }
  resume() {
    this.stopped = false;
  }
  snapshot() {
    return {
      queued: [...this.jobs.values()].filter((j) => !j.started).length,
      active: this.activePlays.size,
      jobs: [...this.jobs.values()].map((j) => this.publicJob(j)),
    };
  }
}
