import express from 'express';
import {z} from 'zod';
import type {LocalConfig} from './config.js';
import {GameSession,GameError} from './game.js';
import {createGameAI,type GameAI} from './game-ai.js';
import {decodePhotos} from './photo.js';
import {liveEventSchema,liveInstructions,factCommand,openingCommand} from './live.js';
import {errorResponse} from '../../packages/server/http.js';
export function createPlayRouter(config:LocalConfig,options:{ai?:GameAI;onEnd?:()=>void;fetch?:typeof fetch}={}){
 const router=express.Router();const request=options.fetch??fetch;let token:string|null=null,liveId:string|null=null,liveToken:string|null=null,liveCreating=false;let model='';let generation=0;let lastHeartbeat=performance.now();let transcriptTimer:ReturnType<typeof setTimeout>|undefined;const seen=new Set<string>();let closing:Promise<void>|null=null;let endingTimer:ReturnType<typeof setTimeout>|undefined;
 async function call(path:string,body?:unknown,authToken=token):Promise<any>{
 const response=await request(config.relayUrl+path,{method:body===undefined?'GET':'POST',headers:{...(body===undefined?{}:{'content-type':'application/json'}),...(authToken?{authorization:'Bearer '+authToken}:{})},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(30_000),redirect:'error'});
 if(!response.ok){await response.body?.cancel();throw new GameError(response.status===401?401:response.status===429?429:502,'AI中継との通信に失敗しました。合言葉・利用上限・接続を確認してください。');}
 if(!response.body)throw new Error('Missing relay body');const reader=response.body.getReader();let length=0;const chunks:Uint8Array[]=[];try{for(;;){const part=await reader.read();if(part.done)break;length+=part.value.length;if(length>256*1024){await reader.cancel();throw new Error('Relay response too large');}chunks.push(part.value);}}finally{reader.releaseLock();}return JSON.parse(Buffer.concat(chunks).toString('utf8'));
 }
 async function closeLive(){if(closing)return closing;if(!liveId)return;const id=liveId;closing=(async()=>{await call('/v1/live/'+encodeURIComponent(id)+'/hangup',{},liveToken);if(liveId===id){liveId=null;liveToken=null;}})().finally(()=>{closing=null;});return closing;}
 const ai=options.ai??createGameAI(call,()=>model);
 function makeSession(){const value=new GameSession(config.scenario,ai,undefined,()=>{clearTimeout(transcriptTimer);seen.clear();if(value.status==='won'||value.status==='lost'){endingTimer=setTimeout(()=>{void closeLive().catch(()=>{});},12_000);endingTimer.unref();}else{void closeLive().catch(()=>{});}options.onEnd?.();});value.generation=++generation;return value;}
 let game=makeSession();
 const tick=setInterval(()=>{game.check();if(liveId&&performance.now()-lastHeartbeat>30_000)game.heartbeat('disconnected');},1000);tick.unref();
 function endpoint(handler:(body:any)=>Promise<unknown>|unknown){return async(req:express.Request,res:express.Response)=>{try{res.json(await handler(req.body));}catch(error){if(error instanceof GameError)errorResponse(res,error.status,'PLAY_ERROR',error.message);else if(error instanceof z.ZodError)errorResponse(res,400,'INVALID_REQUEST','送信内容を確認してください。');else errorResponse(res,502,'PLAY_FAILED','処理に失敗しました。再試行してください。');}};}
 router.put('/photos',express.json({limit:6*1024*1024,inflate:false}),endpoint(async body=>{const parsed=z.object({images:z.array(z.string().max(2796204)).max(config.scenario.rules.maxPhotosPerAction)}).strict().parse(body);const current=game,ticket=current.beginPhotos();try{const photos=await decodePhotos(parsed.images,config.scenario.rules.maxPhotosPerAction);await current.finishPhotos(photos,ticket);return current.state();}catch(error){current.cancelPhotos();if(error instanceof GameError)throw error;throw new GameError(422,'写真を読み取れませんでした。JPEG/PNG/WebP、1枚2MiB以内で撮り直してください。');}}));
 router.post('/live',express.json({limit:72*1024,inflate:false}),async(req,res)=>{try{
 const body=z.object({sdp:z.string().min(1).max(65536),passphrase:z.string().max(256).optional()}).strict().parse(req.body);game.check();if(game.terminal)throw new GameError(410,'プレイは終了しています。');if(liveCreating)throw new GameError(409,'接続処理中です。');liveCreating=true;const current=game;
 try{await closeLive();if(!token){const health=await call('/health');if(health.mode!=='live')throw new GameError(409,'実音声には運営中継のlive設定が必要です。');model=z.string().min(1).parse(health.models?.responses??health.responsesModel);const auth=await call('/v1/sessions',body.passphrase===undefined?{}:{passphrase:body.passphrase});token=z.string().regex(/^[a-f0-9]{64}$/).parse(auth.token);}
 if(current!==game||current.terminal)throw new GameError(410,'プレイが失効しました。');const creatingToken=token;const value=await call('/v1/live/sessions',{session:{model:'gpt-live-1',instructions:liveInstructions(current.state()),delegation:{type:'client'},store:false},transport:{type:'webrtc',sdp:body.sdp}});const parsed=z.object({session:z.object({id:z.string().min(1).max(200)}),transport:z.object({type:z.literal('webrtc'),sdp:z.string().max(65536)})}).parse(value);liveId=parsed.session.id;liveToken=creatingToken;if(current!==game||current.terminal){await closeLive();throw new GameError(410,'プレイが失効しました。');}current.generation=++generation;seen.clear();current.heartbeat('connecting');lastHeartbeat=performance.now();res.status(201).json({sdp:parsed.transport.sdp,generation:current.generation,opening:openingCommand(current.state())});
 }finally{liveCreating=false;}
 }catch(error){if(error instanceof GameError)errorResponse(res,error.status,'LIVE_FAILED',error.message);else errorResponse(res,502,'LIVE_FAILED','音声接続に失敗しました。再接続をタップしてください。');}});
 router.use(express.json({limit:32*1024,inflate:false}));
 router.get('/state',endpoint(()=>game.state()));router.post('/start',endpoint(()=>({...game.start(),commands:[factCommand('導入チュートリアルは終了。本編を開始し、制限時間が進んでいます。現在の障害について相談を続けてください。')]})));
 router.post('/heartbeat',endpoint(async body=>{const value=z.object({generation:z.number().int().nonnegative(),voiceState:z.enum(['connecting','connected','disconnected','failed','closed'])}).strict().parse(body);if(value.generation!==game.generation)throw new GameError(409,'古い音声接続です。');game.heartbeat(value.voiceState);lastHeartbeat=performance.now();if(value.voiceState==='disconnected'||value.voiceState==='failed')await closeLive();if(liveId&&!game.terminal)await call('/v1/live/'+encodeURIComponent(liveId)+'/heartbeat',{});return game.state();}));
 router.post('/events',endpoint(async body=>{const value=z.object({generation:z.number().int().nonnegative(),event:liveEventSchema}).strict().parse(body);if(value.generation!==game.generation)throw new GameError(409,'古い音声接続です。');const current=game,event=value.event;if(seen.has(event.event_id))return{state:current.state(),commands:[]};if(seen.size>=10000)throw new GameError(429,'音声イベント上限です。');seen.add(event.event_id);
 if(event.type==='session.input_transcript.delta'){current.appendTranscript(event.delta);clearTimeout(transcriptTimer);transcriptTimer=setTimeout(()=>{if(current===game&&!current.terminal)void current.recognize().catch(()=>{});},800);}
 if(event.type==='session.delegation.created'){clearTimeout(transcriptTimer);await current.recognize();if(current!==game||current.terminal||value.generation!==current.generation)return{state:game.state(),commands:[]};return{state:current.state(),commands:[factCommand(current.proposal?JSON.stringify(current.proposal):'道具と使い方を確認中。実行はまだ確定していません。',event.delegation.id)]};}
 return{state:current.state(),commands:[]};}));
 router.post('/actions',endpoint(async body=>{const value=z.object({actionId:z.string().uuid(),proposalRevision:z.number().int().positive()}).strict().parse(body);const current=game;const result=await current.commit(value.actionId,value.proposalRevision);return{state:current.state(),commands:[factCommand('確定した行動結果: '+result.narrative+' 現在の状況: '+current.state().situation),{...factCommand('結果を短く伝えてください: '+result.narrative+' 現在の状況: '+current.state().situation),type:'session.commentary.append'}]};}));
 router.post('/end',endpoint(async()=>{game.end();await closeLive();return game.state();}));
 return{router,getState:()=>game.state(),async reset(){clearTimeout(endingTimer);game.end();await closeLive();token=null;seen.clear();game=makeSession();},async dispose(){clearTimeout(endingTimer);clearInterval(tick);clearTimeout(transcriptTimer);game.end();await closeLive();}};
}
